/* ================================================================
   masilmap — fixture data
   건축물 / 컬렉션 / 매거진 항목. 실제 한국 건축물에서 영감을 받은
   픽션 + 실제 이름의 혼합. 모든 카피는 오리지널.
   ================================================================ */

const BUILDINGS = [
  {
    id: "kongkan",
    no: "001",
    name: "공간 사옥",
    nameEn: "SPACE Group Building",
    architect: "김수근",
    year: 1977,
    region: "서울 종로",
    address: "서울 종로구 율곡로 83",
    type: "사무소·갤러리",
    typeKey: "modern",
    style: "한국 모더니즘",
    palette: "#7B4A2E",
    intro: "담쟁이덩굴이 외벽을 뒤덮은 검은 벽돌 건물. 좁고 깊은 동선이 도시의 골목을 닮았다.",
    longRead: "원서동 골목 한 켠, 인사동에서 북촌으로 넘어가는 길에 자리한 검은 벽돌 건물. 김수근이 1971년부터 1977년까지 두 동을 나누어 지었고, 좁고 어둑한 계단실과 갑작스레 열리는 작은 마당이 한국 전통 건축의 동선을 현대어로 옮긴 작품으로 평가받는다. 외벽을 덮은 담쟁이덩굴은 매년 가을마다 건물 전체를 붉게 물들인다.",
    coord: [780, 320],
    metrics: { rooms: 12, floors: 5, gfa: "1,420㎡", visit: "예약제" },
    tags: ["벽돌", "1970s", "모더니즘", "문화재"],
    pinTone: "terra",
    visited: 1284,
    saved: 312,
  },
  {
    id: "whanki",
    no: "002",
    name: "환기미술관",
    nameEn: "Whanki Museum",
    architect: "우규승",
    year: 1992,
    region: "서울 종로",
    address: "서울 종로구 자하문로40길 63",
    type: "미술관",
    typeKey: "museum",
    style: "콘크리트 모더니즘",
    palette: "#7E8A6E",
    intro: "북악산 자락에 안긴 콘크리트 군. 빛이 천창을 통해 천천히 내려앉는 곳.",
    longRead: "부암동 산자락에 흩어진 세 채의 콘크리트 건축. 김환기 화백의 점화(點畵)에서 모티프를 가져왔다는 천창의 빛이 전시실 한가운데로 내려앉고, 관람객은 자연스레 그림이 아닌 빛을 따라 걷게 된다. 정원과 전시실의 경계가 흐려지는 봄에 가장 좋다.",
    coord: [620, 240],
    metrics: { rooms: 8, floors: 3, gfa: "3,200㎡", visit: "상시" },
    tags: ["콘크리트", "1990s", "미술관", "산"],
    pinTone: "olive",
    visited: 4421,
    saved: 928,
  },
  {
    id: "buseoksa",
    no: "003",
    name: "부석사 무량수전",
    nameEn: "Muryangsujeon, Buseoksa",
    architect: "고려 도공",
    year: 1376,
    region: "경북 영주",
    address: "경북 영주시 부석면 부석사로 345",
    type: "전통 사찰",
    typeKey: "hanok",
    style: "고려 목조 건축",
    palette: "#A4422A",
    intro: "산 능선이 멀리 겹쳐 보이는 자리. 기둥의 배흘림이 가장 오래된 호흡을 한다.",
    longRead: "고려 후기에 세워진 한국 최고(最古)의 목조 건축 중 하나. 마당 끝에서 봤을 때 백두대간의 능선이 처마 너머로 겹쳐 보이도록 자리를 잡았고, 굵은 배흘림기둥이 천 년의 무게를 받치고 서 있다. 가을 단풍과 함께 보면 흙·나무·산이 한 호흡으로 정렬된다.",
    coord: [1080, 580],
    metrics: { rooms: 1, floors: 1, gfa: "143㎡", visit: "상시" },
    tags: ["고려", "목조", "국보", "사찰"],
    pinTone: "terra",
    visited: 7821,
    saved: 1340,
  },
  {
    id: "boan",
    no: "004",
    name: "통의동 보안여관",
    nameEn: "Boan 1942",
    architect: "미상",
    year: 1942,
    region: "서울 종로",
    address: "서울 종로구 효자로 33",
    type: "문화공간 (구 여관)",
    typeKey: "modern",
    style: "근대 적산가옥",
    palette: "#8A7A65",
    intro: "시인 서정주가 묵었다는 옛 여관. 삐걱이는 마룻바닥에 새 전시가 걸린다.",
    longRead: "1942년 지어진 작은 여관. 70여 년간 시인과 화가가 묵으며 글과 그림을 남겼고, 2007년 마지막 손님이 떠난 뒤 문화공간으로 다시 문을 열었다. 삐걱이는 복도와 좁은 방의 비례는 그대로 두고, 옆 동에 콘크리트 신관을 덧붙여 옛것과 새것을 마주 보게 했다.",
    coord: [740, 300],
    metrics: { rooms: 14, floors: 2, gfa: "210㎡", visit: "전시 기간" },
    tags: ["근대", "리노베이션", "갤러리"],
    pinTone: "terra",
    visited: 2156,
    saved: 478,
  },
  {
    id: "bonte",
    no: "005",
    name: "본태박물관",
    nameEn: "Bonte Museum",
    architect: "안도 다다오",
    year: 2012,
    region: "제주 서귀포",
    address: "제주 서귀포시 산록남로762번길 69",
    type: "박물관",
    typeKey: "museum",
    style: "노출 콘크리트",
    palette: "#6B6B6B",
    intro: "한라산 중턱의 회색 상자들. 물·돌·콘크리트가 한 화면에 정렬된다.",
    longRead: "한라산 기슭의 완만한 경사를 따라 다섯 개의 직육면체가 어긋나게 놓여 있다. 안도 다다오 특유의 빛 우물, 좁고 긴 진입로, 거울처럼 가라앉은 수공간. 한국 전통 보자기·소반과 현대 콘크리트가 한 공간에서 마주 보는 박물관.",
    coord: [880, 980],
    metrics: { rooms: 5, floors: 2, gfa: "5,800㎡", visit: "상시" },
    tags: ["콘크리트", "2010s", "박물관", "제주"],
    pinTone: "olive",
    visited: 9203,
    saved: 2104,
  },
  {
    id: "soeul",
    no: "006",
    name: "솔올미술관",
    nameEn: "Solwol Museum",
    architect: "리처드 마이어",
    year: 2024,
    region: "강원 강릉",
    address: "강원 강릉시 솔올로 119",
    type: "미술관",
    typeKey: "museum",
    style: "백색 모더니즘",
    palette: "#E8E2D4",
    intro: "동해를 마주 본 백색 입방체. 빛의 결을 가장 정직하게 받아내는 곳.",
    longRead: "강릉 솔숲 한가운데 세워진 흰색 입방체 군. 리처드 마이어 특유의 격자 입면과 둥근 곡선이 만나는 진입홀에서 동해의 빛이 정면으로 들어온다. 흰 벽과 그림자만으로 공간이 구성되는, 한국에 보기 드문 빛 중심 건축.",
    coord: [1020, 380],
    metrics: { rooms: 9, floors: 3, gfa: "6,400㎡", visit: "상시" },
    tags: ["백색", "2020s", "미술관", "바다"],
    pinTone: "terra",
    visited: 3402,
    saved: 891,
  },
  {
    id: "jongmyo",
    no: "007",
    name: "종묘 정전",
    nameEn: "Jongmyo Jeongjeon",
    architect: "조선 도공",
    year: 1395,
    region: "서울 종로",
    address: "서울 종로구 종로 157",
    type: "왕실 사당",
    typeKey: "hanok",
    style: "조선 의례 건축",
    palette: "#5A4332",
    intro: "길이 109m, 한국에서 가장 긴 목조 건물. 비례만으로 위엄이 만들어진다.",
    longRead: "조선 왕실의 신주를 모신 사당. 동서로 109미터 길게 뻗은 단일 건물로, 한국에서 가장 긴 목조 구조물이다. 19칸의 같은 비례가 끝없이 반복되는 입면은 미니멀리즘의 원형으로 자주 인용된다. 비 오는 날 회랑을 따라 걸으면 그 비례가 가장 정확히 느껴진다.",
    coord: [800, 340],
    metrics: { rooms: 19, floors: 1, gfa: "1,270㎡", visit: "해설 동반" },
    tags: ["조선", "유네스코", "목조", "회랑"],
    pinTone: "terra",
    visited: 5638,
    saved: 1102,
  },
  {
    id: "ddp",
    no: "008",
    name: "동대문디자인플라자",
    nameEn: "Dongdaemun Design Plaza",
    architect: "자하 하디드",
    year: 2014,
    region: "서울 중구",
    address: "서울 중구 을지로 281",
    type: "복합문화시설",
    typeKey: "modern",
    style: "비정형 파라메트릭",
    palette: "#A6A6A6",
    intro: "도시 한가운데 떨어진 은빛 액체. 어떤 각도에서도 같은 면을 갖지 않는다.",
    longRead: "옛 동대문운동장 자리에 들어선 비정형 건축. 4만 5천 장의 알루미늄 패널이 모두 다른 크기와 곡률로 외피를 이루고, 보행자는 건물의 어느 면도 정면으로 마주할 수 없다. 야간 조명이 들어올 때 가장 비현실적인 풍경이 된다.",
    coord: [830, 380],
    metrics: { rooms: 25, floors: 4, gfa: "86,574㎡", visit: "상시" },
    tags: ["파라메트릭", "2010s", "공공", "야경"],
    pinTone: "olive",
    visited: 12480,
    saved: 2940,
  },
  {
    id: "leeum",
    no: "009",
    name: "리움미술관",
    nameEn: "Leeum Museum of Art",
    architect: "마리오 보타·장 누벨·렘 콜하스",
    year: 2004,
    region: "서울 용산",
    address: "서울 용산구 이태원로55길 60",
    type: "미술관",
    typeKey: "museum",
    style: "세 거장의 협업",
    palette: "#8C5A3E",
    intro: "세 명의 건축가가 각자 다른 언어로 지은 세 채의 미술관.",
    longRead: "마리오 보타의 테라코타 원통, 장 누벨의 부식 스테인리스 상자, 렘 콜하스의 검은 콘크리트 블록 — 한 부지에 세 거장이 각자 다른 재료와 형식으로 지은 미술관. 사이를 잇는 진입홀에서 세 건축이 동시에 보이는 그 짧은 순간이 이 건축의 핵심이다.",
    coord: [780, 410],
    metrics: { rooms: 14, floors: 4, gfa: "27,367㎡", visit: "상시" },
    tags: ["콜라보", "2000s", "테라코타", "현대미술"],
    pinTone: "terra",
    visited: 8742,
    saved: 1923,
  },
];

const COLLECTIONS = [
  {
    id: "brick",
    no: "Vol.01",
    title: "벽돌의 시간",
    subtitle: "한국 모더니즘 건축 8선",
    editor: "이주영",
    editorRole: "건축평론가",
    issue: "2026 봄호",
    cover: "#7B4A2E",
    blurb: "1960년대부터 90년대까지, 한국 건축가들이 벽돌이라는 가장 가난한 재료를 어떻게 시(詩)로 만들었는지에 대한 기록.",
    count: 8,
    readTime: 14,
    buildings: ["kongkan", "boan", "whanki"],
    tag: "EDITORIAL",
  },
  {
    id: "hanok",
    no: "Vol.02",
    title: "한옥, 다시 짓다",
    subtitle: "21세기 한옥 프로젝트 12선",
    editor: "박정현",
    editorRole: "건축사학자",
    issue: "2026 봄호",
    cover: "#A4422A",
    blurb: "옛 한옥의 형식을 그대로 두지 않고, 다시 쓰고 다시 짓는 사람들. 보존이 아닌 사용에 대한 이야기.",
    count: 12,
    readTime: 18,
    buildings: ["buseoksa", "jongmyo"],
    tag: "FEATURE",
  },
  {
    id: "concrete",
    no: "Vol.03",
    title: "콘크리트와 빛",
    subtitle: "한국의 미술관 산책",
    editor: "최은영",
    editorRole: "큐레이터",
    issue: "2026 봄호",
    cover: "#6B6B6B",
    blurb: "회색 한 가지 재료로도 빛은 매번 다르게 떨어진다. 한국에 지어진 콘크리트 미술관 일곱 곳을 천천히 걸었다.",
    count: 7,
    readTime: 22,
    buildings: ["bonte", "leeum", "soeul"],
    tag: "JOURNEY",
  },
  {
    id: "sea",
    no: "Vol.04",
    title: "바다 곁의 집들",
    subtitle: "동해안 건축 여행",
    editor: "김도윤",
    editorRole: "여행 작가",
    issue: "2026 봄호",
    cover: "#3E6A78",
    blurb: "강릉부터 양양, 속초까지 — 동해를 마주 본 작은 미술관과 카페, 그리고 집들. 차로 닿을 수 있는 거리의 건축 여행.",
    count: 9,
    readTime: 16,
    buildings: ["soeul"],
    tag: "TRAVEL",
  },
  {
    id: "alley",
    no: "Vol.05",
    title: "도시의 틈",
    subtitle: "골목 건축 다시 보기",
    editor: "한지수",
    editorRole: "도시연구자",
    issue: "2025 겨울호",
    cover: "#788B4A",
    blurb: "큰 건축물이 아닌, 골목과 골목 사이에 끼어 있는 작은 집들. 도시를 만드는 진짜 재료에 대하여.",
    count: 11,
    readTime: 12,
    buildings: ["boan"],
    tag: "ESSAY",
  },
  {
    id: "night",
    no: "Vol.06",
    title: "밤의 건축",
    subtitle: "야간 개장하는 공간들",
    editor: "윤서경",
    editorRole: "사진가",
    issue: "2025 겨울호",
    cover: "#1F2230",
    blurb: "해가 진 뒤에야 본래의 얼굴이 드러나는 건축들. 동대문에서 한강까지, 서울의 야경 건축 8선.",
    count: 8,
    readTime: 10,
    buildings: ["ddp", "leeum"],
    tag: "NIGHT",
  },
];

const REGIONS = [
  { id: "seoul", name: "서울", count: 142 },
  { id: "gyeonggi", name: "경기", count: 87 },
  { id: "gangwon", name: "강원", count: 54 },
  { id: "chungcheong", name: "충청", count: 41 },
  { id: "jeolla", name: "전라", count: 68 },
  { id: "gyeongsang", name: "경상", count: 96 },
  { id: "jeju", name: "제주", count: 38 },
];

const TYPES = [
  { id: "all",    name: "전체",        count: 526 },
  { id: "hanok",  name: "한옥·전통",   count: 124 },
  { id: "modern", name: "근현대",      count: 218 },
  { id: "museum", name: "미술관",      count: 87  },
  { id: "religi", name: "종교 건축",   count: 64  },
  { id: "house",  name: "주택",        count: 33  },
];

/* ---------- 마실 코스 (큐레이션 워크) ---------- */
const COURSES = [
  {
    id: "bukchon",
    no: "C-01",
    name: "북촌 골목, 모더니즘과 한옥 사이",
    blurb: "김수근의 검은 벽돌부터 종묘의 회랑까지 — 종로 한복판을 천천히 가로지르는 4시간.",
    curator: { name: "현지", initial: "현", role: "동네 8년차 · 종로 거주", color: "#D26A4E", verified: true },
    rating: 4.8, reviews: 134, visited: 1284, saved: 412,
    distance: "4.2km", duration: "3시간 40분", elevation: "+120m", difficulty: "보통",
    buildings: ["boan", "kongkan", "jongmyo"],
    type: "도슨트", price: 32000, hasDocent: true,
    schedule: ["10:00", "14:00", "16:30"],
    meetingPoint: "지하철 3호선 안국역 1번 출구",
    cover: "#7B4A2E",
  },
  {
    id: "concrete",
    no: "C-02",
    name: "콘크리트와 빛, 미술관 산책",
    blurb: "리움부터 본태박물관까지 — 콘크리트 한 가지 재료로 빛이 매번 다르게 떨어지는 곳들.",
    curator: { name: "은영", initial: "은", role: "큐레이터 · 미술관 12년", color: "#788B4A", verified: true },
    rating: 4.9, reviews: 87, visited: 921, saved: 280,
    distance: "1박 2일", duration: "이틀", elevation: "비행기 필요", difficulty: "여행",
    buildings: ["leeum", "bonte", "whanki"],
    type: "도슨트", price: 280000, hasDocent: true,
    schedule: ["주말 1박 2일 · 월 1회"],
    meetingPoint: "서울역 KTX 출구",
    cover: "#6B6B6B",
  },
  {
    id: "buseoksa",
    no: "C-03",
    name: "영주 부석사, 가을 단풍과 배흘림기둥",
    blurb: "천 년 된 목조 건축을 가장 좋은 빛에서 보는 한나절. 단풍 끝물에 맞춰 운영.",
    curator: { name: "도윤", initial: "도", role: "건축사학자", color: "#A4422A", verified: true },
    rating: 4.7, reviews: 58, visited: 482, saved: 198,
    distance: "당일 왕복", duration: "8시간", elevation: "+180m", difficulty: "쉬움",
    buildings: ["buseoksa"],
    type: "도슨트", price: 78000, hasDocent: true,
    schedule: ["10/15", "10/22", "10/29 · 한정"],
    meetingPoint: "동서울터미널 09:00",
    cover: "#A4422A",
  },
  {
    id: "ddp-night",
    no: "C-04",
    name: "동대문 야간 건축 투어",
    blurb: "해가 진 뒤에야 본래의 얼굴이 드러나는 비정형 건축, 그리고 주변 가로의 변화.",
    curator: { name: "서경", initial: "서", role: "사진가", color: "#1F2230", verified: false },
    rating: 4.6, reviews: 41, visited: 386, saved: 102,
    distance: "1.8km", duration: "2시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["ddp"],
    type: "셀프", price: 0, hasDocent: false,
    schedule: ["언제든 · 19:30 ~"],
    meetingPoint: "동대문디자인플라자 1번 입구",
    cover: "#1F2230",
  },
];

/* ---------- 외부 공간 (숙박/식음/체험) ---------- */
const EXTERNAL_SPACES = [
  {
    id: "boanstay",
    name: "보안스테이 1942",
    building: "boan",
    type: "숙박", typeIcon: "🛏",
    summary: "통의동 보안여관의 신관. 옛 여관의 비례를 살린 5개 객실.",
    partner: "마이리얼트립", partnerLogo: "MRT",
    minPrice: 220000,
    href: "#",
  },
  {
    id: "sansacafe",
    name: "산사 다실",
    building: "buseoksa",
    type: "식음", typeIcon: "🍵",
    summary: "부석사 진입로 옆 작은 다실. 산에서 길어 올린 물로 차를 낸다.",
    partner: "캐치테이블", partnerLogo: "CT",
    minPrice: 18000,
    href: "#",
  },
  {
    id: "jejuworkshop",
    name: "콘크리트 워크숍",
    building: "bonte",
    type: "체험", typeIcon: "🧱",
    summary: "안도 다다오 건축을 모티프로 한 콘크리트 소품 만들기 (2시간).",
    partner: "프립", partnerLogo: "FR",
    minPrice: 65000,
    href: "#",
  },
];

/* ---------- 유저 ---------- */
const USER = {
  name: "민서",
  handle: "@minseo",
  initial: "민",
  color: "#D26A4E",
  joined: "2024년 3월",
  bio: "걷는 속도로 도시를 보는 사람. 한옥과 콘크리트를 똑같이 좋아함.",
  visitedCount: 23,
  savedBuildings: 47,
  savedCourses: 8,
  following: 12,
  followers: 38,
};

/* ---------- 예약 내역 ---------- */
const BOOKINGS = [
  {
    id: "B2026-0418",
    courseId: "bukchon",
    date: "2026.06.15 (토)",
    time: "10:00",
    people: 2,
    price: 64000,
    status: "예정",
  },
  {
    id: "B2026-0301",
    courseId: "concrete",
    date: "2026.07.20 (토) ~ 21",
    time: "1박 2일",
    people: 1,
    price: 280000,
    status: "예정",
  },
  {
    id: "B2025-1124",
    courseId: "ddp-night",
    date: "2025.11.18 (화)",
    time: "19:30",
    people: 3,
    price: 0,
    status: "완료",
  },
];

/* ---------- 권리 관리용 자료 (관리자 화면) ---------- */
const ASSETS = [
  { id: "A-3201", building: "kongkan", name: "공간사옥_외관_가을_001.jpg",  type: "사진",      uploader: "한지수", owner: "한지수",          consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3202", building: "kongkan", name: "공간사옥_평면도_원본.pdf",     type: "도면",      uploader: "마실맵", owner: "건축가 유족",      consent: "대기", split: "유족 60% · 마실맵 40%",        status: "대기" },
  { id: "A-3203", building: "whanki",  name: "환기미술관_3D모델_v2.glb",    type: "3D",        uploader: "우규승", owner: "우규승 외 2명",    consent: "보류", split: "설계자 50% · 협력 30% · 마실맵 20%", status: "보류" },
  { id: "A-3204", building: "buseoksa",name: "부석사_무량수전_드론_004.jpg", type: "사진",      uploader: "도윤",   owner: "도윤",            consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3205", building: "leeum",   name: "리움_진입홀_다이어그램.svg",   type: "다이어그램", uploader: "은영",   owner: "은영",            consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3206", building: "ddp",     name: "DDP_야간_시퀀스_012.jpg",     type: "사진",      uploader: "서경",   owner: "서경 외 1명",      consent: "대기", split: "촬영 70% · 스타일링 30%",     status: "대기" },
  { id: "A-3207", building: "bonte",   name: "본태_평면배치.pdf",           type: "도면",      uploader: "마실맵", owner: "안도다다오 사무소", consent: "보류", split: "원저작자 80% · 마실맵 20%",    status: "보류" },
  { id: "A-3208", building: "boan",    name: "보안여관_재현_도면.dwg",       type: "도면",      uploader: "마실맵", owner: "마실맵",          consent: "완료", split: "100%",                       status: "공개" },
];

Object.assign(window, { BUILDINGS, COLLECTIONS, REGIONS, TYPES, COURSES, EXTERNAL_SPACES, USER, BOOKINGS, ASSETS });
