/* ================================================================
   masilmap — fixture data
   건축물 / 컬렉션 / 매거진 항목. 실제 한국 건축물에서 영감을 받은
   픽션 + 실제 이름의 혼합. 모든 카피는 오리지널.
   ================================================================ */

const BUILDINGS = [
  {
    id: "kongkan",
    no: "001",
    name: "공간 사옥",
    nameEn: "SPACE Group Building",
    architect: "김수근",
    year: 1977,
    region: "서울 종로",
    address: "서울 종로구 율곡로 83",
    type: "사무소·갤러리",
    typeKey: "modern",
    useKey: "office-general",
    style: "한국 모더니즘",
    palette: "#333D51",
    intro: "담쟁이덩굴이 외벽을 뒤덮은 검은 벽돌 건물. 좁고 깊은 동선이 도시의 골목을 닮았다.",
    longRead: "원서동 골목 한 켠, 인사동에서 북촌으로 넘어가는 길에 자리한 검은 벽돌 건물. 김수근이 1971년부터 1977년까지 두 동을 나누어 지었고, 좁고 어둑한 계단실과 갑작스레 열리는 작은 마당이 한국 전통 건축의 동선을 현대어로 옮긴 작품으로 평가받는다. 외벽을 덮은 담쟁이덩굴은 매년 가을마다 건물 전체를 붉게 물들인다.",
    coord: [780, 320],
    metrics: { rooms: 12, floors: 5, gfa: "1,420㎡", visit: "예약제" },
    tags: ["벽돌", "1970s", "모더니즘", "문화재"],
    pinTone: "terra",
    visited: 1284,
    saved: 312,
  },
  {
    id: "whanki",
    no: "002",
    name: "환기미술관",
    nameEn: "Whanki Museum",
    architect: "우규승",
    year: 1992,
    region: "서울 종로",
    address: "서울 종로구 자하문로40길 63",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "콘크리트 모더니즘",
    palette: "#7E8A6E",
    intro: "북악산 자락에 안긴 콘크리트 군. 빛이 천창을 통해 천천히 내려앉는 곳.",
    longRead: "부암동 산자락에 흩어진 세 채의 콘크리트 건축. 김환기 화백의 점화(點畵)에서 모티프를 가져왔다는 천창의 빛이 전시실 한가운데로 내려앉고, 관람객은 자연스레 그림이 아닌 빛을 따라 걷게 된다. 정원과 전시실의 경계가 흐려지는 봄에 가장 좋다.",
    coord: [620, 240],
    metrics: { rooms: 8, floors: 3, gfa: "3,200㎡", visit: "상시" },
    tags: ["콘크리트", "1990s", "미술관", "산"],
    pinTone: "olive",
    visited: 4421,
    saved: 928,
  },
  {
    id: "buseoksa",
    no: "003",
    name: "부석사 무량수전",
    nameEn: "Muryangsujeon, Buseoksa",
    architect: "고려 도공",
    year: 1376,
    region: "경북 영주",
    address: "경북 영주시 부석면 부석사로 345",
    type: "전통 사찰",
    typeKey: "hanok",
    useKey: "museum",
    style: "고려 목조 건축",
    palette: "#9C7E1A",
    intro: "산 능선이 멀리 겹쳐 보이는 자리. 기둥의 배흘림이 가장 오래된 호흡을 한다.",
    longRead: "고려 후기에 세워진 한국 최고(最古)의 목조 건축 중 하나. 마당 끝에서 봤을 때 백두대간의 능선이 처마 너머로 겹쳐 보이도록 자리를 잡았고, 굵은 배흘림기둥이 천 년의 무게를 받치고 서 있다. 가을 단풍과 함께 보면 흙·나무·산이 한 호흡으로 정렬된다.",
    coord: [1080, 580],
    metrics: { rooms: 1, floors: 1, gfa: "143㎡", visit: "상시" },
    tags: ["고려", "목조", "국보", "사찰"],
    pinTone: "terra",
    visited: 7821,
    saved: 1340,
  },
  {
    id: "boan",
    no: "004",
    name: "통의동 보안여관",
    nameEn: "Boan 1942",
    architect: "미상",
    year: 1942,
    region: "서울 종로",
    address: "서울 종로구 효자로 33",
    type: "문화공간 (구 여관)",
    typeKey: "modern",
    useKey: "exhibit-hall",
    style: "근대 적산가옥",
    palette: "#8A7A65",
    intro: "시인 서정주가 묵었다는 옛 여관. 삐걱이는 마룻바닥에 새 전시가 걸린다.",
    longRead: "1942년 지어진 작은 여관. 70여 년간 시인과 화가가 묵으며 글과 그림을 남겼고, 2007년 마지막 손님이 떠난 뒤 문화공간으로 다시 문을 열었다. 삐걱이는 복도와 좁은 방의 비례는 그대로 두고, 옆 동에 콘크리트 신관을 덧붙여 옛것과 새것을 마주 보게 했다.",
    coord: [740, 300],
    metrics: { rooms: 14, floors: 2, gfa: "210㎡", visit: "전시 기간" },
    tags: ["근대", "리노베이션", "갤러리"],
    pinTone: "terra",
    visited: 2156,
    saved: 478,
  },
  {
    id: "bonte",
    no: "005",
    name: "본태박물관",
    nameEn: "Bonte Museum",
    architect: "안도 다다오",
    year: 2012,
    region: "제주 서귀포",
    address: "제주 서귀포시 산록남로762번길 69",
    type: "박물관",
    typeKey: "museum",
    useKey: "museum",
    style: "노출 콘크리트",
    palette: "#6B6B6B",
    intro: "한라산 중턱의 회색 상자들. 물·돌·콘크리트가 한 화면에 정렬된다.",
    longRead: "한라산 기슭의 완만한 경사를 따라 다섯 개의 직육면체가 어긋나게 놓여 있다. 안도 다다오 특유의 빛 우물, 좁고 긴 진입로, 거울처럼 가라앉은 수공간. 한국 전통 보자기·소반과 현대 콘크리트가 한 공간에서 마주 보는 박물관.",
    coord: [880, 980],
    metrics: { rooms: 5, floors: 2, gfa: "5,800㎡", visit: "상시" },
    tags: ["콘크리트", "2010s", "박물관", "제주"],
    pinTone: "olive",
    visited: 9203,
    saved: 2104,
  },
  {
    id: "soeul",
    no: "006",
    name: "솔올미술관",
    nameEn: "Solwol Museum",
    architect: "리처드 마이어",
    year: 2024,
    region: "강원 강릉",
    address: "강원 강릉시 솔올로 119",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "백색 모더니즘",
    palette: "#CBD0D8",
    intro: "동해를 마주 본 백색 입방체. 빛의 결을 가장 정직하게 받아내는 곳.",
    longRead: "강릉 솔숲 한가운데 세워진 흰색 입방체 군. 리처드 마이어 특유의 격자 입면과 둥근 곡선이 만나는 진입홀에서 동해의 빛이 정면으로 들어온다. 흰 벽과 그림자만으로 공간이 구성되는, 한국에 보기 드문 빛 중심 건축.",
    coord: [1020, 380],
    metrics: { rooms: 9, floors: 3, gfa: "6,400㎡", visit: "상시" },
    tags: ["백색", "2020s", "미술관", "바다"],
    pinTone: "terra",
    visited: 3402,
    saved: 891,
  },
  {
    id: "jongmyo",
    no: "007",
    name: "종묘 정전",
    nameEn: "Jongmyo Jeongjeon",
    architect: "조선 도공",
    year: 1395,
    region: "서울 종로",
    address: "서울 종로구 종로 157",
    type: "왕실 사당",
    typeKey: "hanok",
    useKey: "museum",
    style: "조선 의례 건축",
    palette: "#1F2738",
    intro: "길이 109m, 한국에서 가장 긴 목조 건물. 비례만으로 위엄이 만들어진다.",
    longRead: "조선 왕실의 신주를 모신 사당. 동서로 109미터 길게 뻗은 단일 건물로, 한국에서 가장 긴 목조 구조물이다. 19칸의 같은 비례가 끝없이 반복되는 입면은 미니멀리즘의 원형으로 자주 인용된다. 비 오는 날 회랑을 따라 걸으면 그 비례가 가장 정확히 느껴진다.",
    coord: [800, 340],
    metrics: { rooms: 19, floors: 1, gfa: "1,270㎡", visit: "해설 동반" },
    tags: ["조선", "유네스코", "목조", "회랑"],
    pinTone: "terra",
    visited: 5638,
    saved: 1102,
  },
  {
    id: "ddp",
    no: "008",
    name: "동대문디자인플라자",
    nameEn: "Dongdaemun Design Plaza",
    architect: "자하 하디드",
    year: 2014,
    region: "서울 중구",
    address: "서울 중구 을지로 281",
    type: "복합문화시설",
    typeKey: "modern",
    useKey: "culture-complex",
    style: "비정형 파라메트릭",
    palette: "#A6A6A6",
    intro: "도시 한가운데 떨어진 은빛 액체. 어떤 각도에서도 같은 면을 갖지 않는다.",
    longRead: "옛 동대문운동장 자리에 들어선 비정형 건축. 4만 5천 장의 알루미늄 패널이 모두 다른 크기와 곡률로 외피를 이루고, 보행자는 건물의 어느 면도 정면으로 마주할 수 없다. 야간 조명이 들어올 때 가장 비현실적인 풍경이 된다.",
    coord: [830, 380],
    metrics: { rooms: 25, floors: 4, gfa: "86,574㎡", visit: "상시" },
    tags: ["파라메트릭", "2010s", "공공", "야경"],
    pinTone: "olive",
    visited: 12480,
    saved: 2940,
  },
  {
    id: "leeum",
    no: "009",
    name: "리움미술관",
    nameEn: "Leeum Museum of Art",
    architect: "마리오 보타·장 누벨·렘 콜하스",
    year: 2004,
    region: "서울 용산",
    address: "서울 용산구 이태원로55길 60",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "세 거장의 협업",
    palette: "#8C5A3E",
    intro: "세 명의 건축가가 각자 다른 언어로 지은 세 채의 미술관.",
    longRead: "마리오 보타의 테라코타 원통, 장 누벨의 부식 스테인리스 상자, 렘 콜하스의 검은 콘크리트 블록 — 한 부지에 세 거장이 각자 다른 재료와 형식으로 지은 미술관. 사이를 잇는 진입홀에서 세 건축이 동시에 보이는 그 짧은 순간이 이 건축의 핵심이다.",
    coord: [780, 410],
    metrics: { rooms: 14, floors: 4, gfa: "27,367㎡", visit: "상시" },
    tags: ["콜라보", "2000s", "테라코타", "현대미술"],
    pinTone: "terra",
    visited: 8742,
    saved: 1923,
  },
  {
    id: "museumsan",
    no: "010",
    name: "뮤지엄 산",
    nameEn: "Museum SAN",
    architect: "안도 다다오",
    year: 2013,
    region: "강원 원주",
    address: "강원 원주시 지정면 오크밸리2길 260",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "노출 콘크리트",
    palette: "#6F6F6F",
    intro: "산 능선 따라 천천히 흐르는 콘크리트 회랑. 빛이 가장 천천히 도달하는 곳.",
    longRead: "한솔재단이 안도 다다오에게 의뢰한 산속 미술관. 워터가든·플라워가든·메인뮤지엄·스톤가든·제임스 터렐관이 200미터 길이의 회랑으로 이어진다. 매 구간 사이마다 좁고 어두운 진입로가 놓이고, 그 끝마다 산능선이 프레임처럼 잘려 들어온다.",
    coord: [880, 360],
    metrics: { rooms: 11, floors: 2, gfa: "12,800㎡", visit: "상시" },
    tags: ["콘크리트", "2010s", "미술관", "산"],
    pinTone: "olive",
    visited: 6840,
    saved: 1842,
  },
  {
    id: "njpcenter",
    no: "011",
    name: "백남준아트센터",
    nameEn: "Nam June Paik Art Center",
    architect: "키르스텐 셰멜·마리나 슈탑",
    year: 2008,
    region: "경기 용인",
    address: "경기 용인시 기흥구 백남준로 10",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "현대 미니멀",
    palette: "#4A5570",
    intro: "작가의 사인 'V'를 위에서 본 평면. 인공의 빛을 가장 정직하게 받쳐주는 검은 건축.",
    longRead: "백남준의 자필 사인 'V'에서 따온 평면이 그대로 건축이 되었다. 곡선 외피의 유리 커튼월 안쪽으로 검은 노출 콘크리트 벽이 미디어 아트의 빛을 흡수한다. 자연광을 거의 차단해, 작가가 평생 다뤘던 '인공의 빛'이 가장 정직하게 작동하도록 설계되었다.",
    coord: [850, 405],
    metrics: { rooms: 7, floors: 3, gfa: "5,460㎡", visit: "상시" },
    tags: ["미디어아트", "2000s", "미술관", "검정"],
    pinTone: "olive",
    visited: 3580,
    saved: 712,
  },
  {
    id: "mmcas",
    no: "012",
    name: "국립현대미술관 서울",
    nameEn: "MMCA Seoul",
    architect: "민현준·mp_art architects",
    year: 2013,
    region: "서울 종로",
    address: "서울 종로구 삼청로 30",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "현대 복합",
    palette: "#B0A99C",
    intro: "옛 기무사 터에 흩어진 작은 매스들. 도시 한가운데서 가장 조용한 진입.",
    longRead: "옛 국군기무사령부 부지에 들어선 미술관. 하나의 거대한 매스가 아니라 여덟 개의 작은 매스가 마당과 광장 사이로 흩어져 있어, 관람객이 미술관을 '걷는' 방식으로 경험하게 한다. 인접한 종친부 건물 한 채를 그대로 보존해 미술관 안에 한옥 한 채가 떠 있다.",
    coord: [790, 335],
    metrics: { rooms: 8, floors: 5, gfa: "52,125㎡", visit: "상시" },
    tags: ["복합", "2010s", "미술관", "도심"],
    pinTone: "terra",
    visited: 10240,
    saved: 2340,
  },
  {
    id: "jongrotower",
    no: "013",
    name: "종로타워",
    nameEn: "Jongno Tower",
    architect: "라파엘 비뇰리",
    year: 1999,
    region: "서울 종로",
    address: "서울 종로구 종로 51",
    type: "사무소",
    typeKey: "modern",
    useKey: "office-general",
    style: "하이테크 모더니즘",
    palette: "#6B6B6B",
    intro: "33층 위에 떠 있는 도넛. 도시가 건물 한가운데를 관통한다.",
    longRead: "옛 화신백화점 자리에 들어선 라파엘 비뇰리의 첫 한국 작업. 24층부터 32층까지가 비어 있고, 그 위에 회의장과 스카이바가 들어 있는 도넛 형태가 떠 있다. 보행자는 1층 로비에서 위를 올려다보면 건물 한가운데로 하늘이 잘려 들어온다.",
    coord: [800, 360],
    metrics: { rooms: 33, floors: 33, gfa: "67,800㎡", visit: "외관 상시" },
    tags: ["하이테크", "1990s", "사옥", "랜드마크"],
    pinTone: "olive",
    visited: 5240,
    saved: 480,
  },
  {
    id: "geunjeongjeon",
    no: "014",
    name: "경복궁 근정전",
    nameEn: "Geunjeongjeon, Gyeongbokgung",
    architect: "조선 도공",
    year: 1395,
    region: "서울 종로",
    address: "서울 종로구 사직로 161",
    type: "왕실 정전",
    typeKey: "hanok",
    useKey: "museum",
    style: "조선 정궐 건축",
    palette: "#8C3D1F",
    intro: "두 단의 월대 위에 올라선 가장 큰 한옥. 모든 한옥의 비례가 여기서 시작된다.",
    longRead: "조선 왕조의 첫 궁궐인 경복궁의 중심 건물. 두 단의 화강암 월대 위에 정면 5칸 측면 5칸의 중층 건물이 올라서 있고, 지붕은 우진각보다 격이 높은 팔작지붕. 임진왜란으로 한 차례 소실되었다가 1867년에 흥선대원군이 중건한 것이 지금 보는 모습이다.",
    coord: [780, 338],
    metrics: { rooms: 1, floors: 2, gfa: "약 950㎡", visit: "상시" },
    tags: ["조선", "정궐", "국보", "한옥"],
    pinTone: "terra",
    visited: 18420,
    saved: 3240,
  },
  {
    id: "yangjindang",
    no: "015",
    name: "양진당",
    nameEn: "Yangjindang House",
    architect: "류운룡",
    year: 1573,
    region: "경북 안동",
    address: "경북 안동시 풍천면 종가길 68",
    type: "종택",
    typeKey: "hanok",
    useKey: "villa",
    style: "조선 종가 한옥",
    palette: "#6B4A30",
    intro: "하회마을 강안 비탈 위에 올라선 종갓집. 사대부 살림의 원형이 가장 정직하게 남았다.",
    longRead: "풍산 류씨 종가. 안채·사랑채·사당이 'ㅁ' 자에 가까운 배치로 둘러서 있고, 사랑채 누마루에서 낙동강 줄기와 마을 어귀가 한 화면에 들어온다. 마루의 깊이와 처마의 깊이, 댓돌의 높이가 모두 그 자리에서의 시선을 위해 정해졌다.",
    coord: [1020, 585],
    metrics: { rooms: 16, floors: 1, gfa: "약 470㎡", visit: "상시" },
    tags: ["조선", "종택", "한옥", "유네스코"],
    pinTone: "terra",
    visited: 2840,
    saved: 482,
  },
  {
    id: "bongjeongsa",
    no: "016",
    name: "봉정사 극락전",
    nameEn: "Geungnakjeon, Bongjeongsa",
    architect: "고려 도공",
    year: 1200,
    region: "경북 안동",
    address: "경북 안동시 서후면 봉정사길 222",
    type: "전통 사찰",
    typeKey: "hanok",
    useKey: "museum",
    style: "고려 목조 건축",
    palette: "#333D51",
    intro: "한국에 남은 가장 오래된 목조 건물. 천 년 동안 같은 자리에 같은 비례로.",
    longRead: "1972년 해체 보수 중 발견된 묵서명에 의해 1363년 이전 건축으로 확인된, 한국에 현존하는 가장 오래된 목조 건축. 정면 3칸 측면 4칸의 작은 맞배지붕 건물로, 부재 하나하나의 비례가 단순하고 강건하다. 부석사 무량수전보다 더 이른 시기의 양식이 남아 있다.",
    coord: [1045, 575],
    metrics: { rooms: 1, floors: 1, gfa: "약 75㎡", visit: "상시" },
    tags: ["고려", "최고", "국보", "사찰"],
    pinTone: "terra",
    visited: 4280,
    saved: 920,
  },
  {
    id: "acc",
    no: "017",
    name: "국립아시아문화전당",
    nameEn: "Asia Culture Center",
    architect: "우규승",
    year: 2015,
    region: "광주 동구",
    address: "광주 동구 문화전당로 38",
    type: "복합문화시설",
    typeKey: "modern",
    useKey: "culture-complex",
    style: "빛의 숲",
    palette: "#5A6B7A",
    intro: "옛 전남도청 위에 비어 있는 광장. 도시의 기억 위로 빛이 떨어진다.",
    longRead: "5·18 광주민주화운동의 무대였던 옛 전남도청을 보존한 위에 들어선 거대 지하 문화시설. 지상은 비어 있는 광장과 '빛의 숲'이라 부르는 천창들로만 표시되고, 모든 프로그램은 지하로 내려간다. 도시의 기억과 새 문화 시설이 한 평면 위에 겹쳐 있다.",
    coord: [580, 720],
    metrics: { rooms: 28, floors: 7, gfa: "161,237㎡", visit: "상시" },
    tags: ["복합", "2010s", "지하", "광주"],
    pinTone: "olive",
    visited: 6420,
    saved: 1102,
  },
  {
    id: "amorepacific",
    no: "018",
    name: "아모레퍼시픽 본사",
    nameEn: "Amorepacific Headquarters",
    architect: "데이비드 치퍼필드",
    year: 2017,
    region: "서울 용산",
    address: "서울 용산구 한강대로 100",
    type: "사옥",
    typeKey: "modern",
    useKey: "office-general",
    style: "미니멀 큐브",
    palette: "#C8C6C0",
    intro: "도시 한복판에 떨어진 큰 정사각형. 사옥의 중정이 도시에 열려 있다.",
    longRead: "한 변 110미터의 정사각 평면. 한가운데에 5층 높이의 정원이 비어 있고, 세 면에 큰 보이드를 두어 도시의 시선이 건물을 관통한다. 알루미늄 수직 루버가 입면 전체를 감싸 햇빛에 따라 표정이 끊임없이 바뀐다. 보존과 변화 사이의 정확한 균형을 사옥 건축으로 보여준다.",
    coord: [780, 420],
    metrics: { rooms: 22, floors: 22, gfa: "188,902㎡", visit: "1층 상시" },
    tags: ["미니멀", "2010s", "사옥", "정원"],
    pinTone: "terra",
    visited: 8920,
    saved: 1840,
  },
  {
    id: "seonyudo",
    no: "019",
    name: "선유도 공원",
    nameEn: "Seonyudo Park",
    architect: "정영선·조성룡",
    year: 2002,
    region: "서울 영등포",
    address: "서울 영등포구 선유로 343",
    type: "도시 공원",
    typeKey: "modern",
    useKey: "visitor-center",
    style: "산업 유산 재생",
    palette: "#4A5570",
    intro: "옛 정수장의 콘크리트 수조를 그대로 두고 정원이 된 한강의 섬.",
    longRead: "1978년부터 2000년까지 한강물을 정화하던 정수장이 있던 한강의 작은 섬. 시설 철거 대신 콘크리트 수조와 펌프장 구조물을 그대로 두고 그 위에 정원·온실·자생식물원을 얹었다. 도시 인프라가 어떻게 두 번째 삶을 갖는지에 대한 한국에서 가장 잘 알려진 사례.",
    coord: [770, 405],
    metrics: { rooms: 6, floors: 1, gfa: "약 11만㎡", visit: "상시" },
    tags: ["산업재생", "2000s", "공원", "한강"],
    pinTone: "olive",
    visited: 14820,
    saved: 2480,
  },
  {
    id: "parkmuseum",
    no: "020",
    name: "박수근미술관",
    nameEn: "Park Soo-keun Museum",
    architect: "이종호",
    year: 2002,
    region: "강원 양구",
    address: "강원 양구군 양구읍 박수근로 265-15",
    type: "미술관",
    typeKey: "museum",
    useKey: "art-museum",
    style: "자연 친화 모더니즘",
    palette: "#6B7484",
    intro: "작가의 화강암 회벽을 건축어로 옮긴 곳. 마을 한복판에 낮게 누운 미술관.",
    longRead: "화가 박수근의 고향 양구에 그의 회벽 같은 질감을 그대로 건축으로 옮긴 작은 미술관. 흙벽돌과 화강암을 거칠게 쌓아 작가의 화면을 입체로 펼쳤고, 마당 한가운데에 작가의 동상이 마을을 바라보고 있다. 이종호 특유의 '풍경에 낮게 누운 건축' 어법이 가장 정제된 형태로 드러난다.",
    coord: [925, 280],
    metrics: { rooms: 5, floors: 2, gfa: "약 1,820㎡", visit: "상시" },
    tags: ["회벽", "2000s", "미술관", "양구"],
    pinTone: "terra",
    visited: 1820,
    saved: 380,
  },
  {
    id: "hangeulmuseum",
    no: "021",
    name: "국립한글박물관",
    nameEn: "National Hangeul Museum",
    architect: "박승홍 (삼우건축)",
    year: 2014,
    region: "서울 용산",
    address: "서울 용산구 서빙고로 139",
    type: "박물관",
    typeKey: "museum",
    useKey: "museum",
    style: "현대 박물관 건축",
    palette: "#7A8497",
    intro: "한글 모음의 곡선을 그대로 입면에 옮긴 박물관. 글자가 건축이 되는 순간.",
    longRead: "용산가족공원 안에 들어선 한글 전용 박물관. ㅏ·ㅓ·ㅗ·ㅜ 같은 한글 모음의 획에서 출발한 곡선과 사선이 입면 전체에 반복된다. 진입로 처마 아래에서 책장이 펼쳐지듯 외피가 펼쳐지는 장면이 이 건축의 한 컷이다. 옆 동의 국립중앙박물관과 마당을 공유한다.",
    coord: [780, 425],
    metrics: { rooms: 6, floors: 3, gfa: "11,322㎡", visit: "상시" },
    tags: ["한글", "2010s", "박물관", "용산"],
    pinTone: "terra",
    visited: 3240,
    saved: 680,
  },
];

const COLLECTIONS = [
  {
    id: "brick",
    no: "Vol.01",
    title: "벽돌의 시간",
    subtitle: "한국 모더니즘 건축 8선",
    editor: "이주영",
    editorRole: "건축평론가",
    issue: "2026 봄호",
    cover: "#333D51",
    blurb: "1960년대부터 90년대까지, 한국 건축가들이 벽돌이라는 가장 가난한 재료를 어떻게 시(詩)로 만들었는지에 대한 기록.",
    count: 8,
    readTime: 14,
    buildings: ["kongkan", "boan", "whanki"],
    tag: "EDITORIAL",
  },
  {
    id: "hanok",
    no: "Vol.02",
    title: "한옥, 다시 짓다",
    subtitle: "21세기 한옥 프로젝트 12선",
    editor: "박정현",
    editorRole: "건축사학자",
    issue: "2026 봄호",
    cover: "#9C7E1A",
    blurb: "옛 한옥의 형식을 그대로 두지 않고, 다시 쓰고 다시 짓는 사람들. 보존이 아닌 사용에 대한 이야기.",
    count: 12,
    readTime: 18,
    buildings: ["buseoksa", "jongmyo"],
    tag: "FEATURE",
  },
  {
    id: "concrete",
    no: "Vol.03",
    title: "콘크리트와 빛",
    subtitle: "한국의 미술관 산책",
    editor: "최은영",
    editorRole: "큐레이터",
    issue: "2026 봄호",
    cover: "#6B6B6B",
    blurb: "회색 한 가지 재료로도 빛은 매번 다르게 떨어진다. 한국에 지어진 콘크리트 미술관 일곱 곳을 천천히 걸었다.",
    count: 7,
    readTime: 22,
    buildings: ["bonte", "leeum", "soeul"],
    tag: "JOURNEY",
  },
  {
    id: "sea",
    no: "Vol.04",
    title: "바다 곁의 집들",
    subtitle: "동해안 건축 여행",
    editor: "김도윤",
    editorRole: "여행 작가",
    issue: "2026 봄호",
    cover: "#2F4858",
    blurb: "강릉부터 양양, 속초까지 — 동해를 마주 본 작은 미술관과 카페, 그리고 집들. 차로 닿을 수 있는 거리의 건축 여행.",
    count: 9,
    readTime: 16,
    buildings: ["soeul"],
    tag: "TRAVEL",
  },
  {
    id: "alley",
    no: "Vol.05",
    title: "도시의 틈",
    subtitle: "골목 건축 다시 보기",
    editor: "한지수",
    editorRole: "도시연구자",
    issue: "2025 겨울호",
    cover: "#5A6B7A",
    blurb: "큰 건축물이 아닌, 골목과 골목 사이에 끼어 있는 작은 집들. 도시를 만드는 진짜 재료에 대하여.",
    count: 11,
    readTime: 12,
    buildings: ["boan"],
    tag: "ESSAY",
  },
  {
    id: "night",
    no: "Vol.06",
    title: "밤의 건축",
    subtitle: "야간 개장하는 공간들",
    editor: "윤서경",
    editorRole: "사진가",
    issue: "2025 겨울호",
    cover: "#1F2738",
    blurb: "해가 진 뒤에야 본래의 얼굴이 드러나는 건축들. 동대문에서 한강까지, 서울의 야경 건축 8선.",
    count: 8,
    readTime: 10,
    buildings: ["ddp", "leeum"],
    tag: "NIGHT",
  },
];

const REGIONS = [
  { id: "seoul", name: "서울", count: 142 },
  { id: "gyeonggi", name: "경기", count: 87 },
  { id: "gangwon", name: "강원", count: 54 },
  { id: "chungcheong", name: "충청", count: 41 },
  { id: "jeolla", name: "전라", count: 68 },
  { id: "gyeongsang", name: "경상", count: 96 },
  { id: "jeju", name: "제주", count: 38 },
];

const TYPES = [
  { id: "all",    name: "전체",        count: 526 },
  { id: "hanok",  name: "한옥·전통",   count: 124 },
  { id: "modern", name: "근현대",      count: 218 },
  { id: "museum", name: "미술관",      count: 87  },
  { id: "religi", name: "종교 건축",   count: 64  },
  { id: "house",  name: "주택",        count: 33  },
];

/* ---------- 건축 용도 (1차 법정용도 → 2차 세부유형 hierarchical) ----------
   각 1차 카테고리가 children 배열로 2차 유형을 가진다.
   buildings의 useKey는 2차 id를 가리킨다. */
const USE_TYPES = [
  { id: "house-single", name: "단독주택", children: [
    { id: "villa", name: "별장" },
  ]},
  { id: "house-multi", name: "공동주택", children: [
    { id: "apartment", name: "공동주택" },
    { id: "dormitory", name: "기숙사" },
    { id: "coliving",  name: "코리빙(공유주거)" },
    { id: "townhouse", name: "타운하우스" },
  ]},
  { id: "nrlf", name: "제1·2종 근린생활시설", children: [
    { id: "cafe", name: "카페" },
  ]},
  { id: "culture", name: "문화 및 집회시설", children: [
    { id: "art-museum",        name: "미술관" },
    { id: "museum",            name: "박물관" },
    { id: "exhibit-hall",      name: "전시장" },
    { id: "performance",       name: "공연예술센터" },
    { id: "culture-complex",   name: "복합문화시설" },
    { id: "multipurpose-hall", name: "다목적홀" },
  ]},
  { id: "retail", name: "판매시설", children: [
    { id: "retail-general", name: "판매시설" },
    { id: "market",         name: "시장" },
    { id: "showroom",       name: "쇼룸" },
  ]},
  { id: "medical", name: "의료시설", children: [
    { id: "hospital",      name: "병원" },
    { id: "health-center", name: "보건소" },
  ]},
  { id: "education", name: "교육연구시설", children: [
    { id: "kindergarten", name: "유치원" },
    { id: "elementary",   name: "초등학교" },
    { id: "secondary",    name: "중·고등학교" },
    { id: "library",      name: "도서관" },
    { id: "edu-center",   name: "교육센터" },
  ]},
  { id: "elderly", name: "노유자시설", children: [
    { id: "care-center", name: "돌봄센터" },
  ]},
  { id: "training", name: "수련시설", children: [
    { id: "youth-center", name: "청소년센터" },
  ]},
  { id: "sports", name: "운동시설", children: [
    { id: "sports-center", name: "스포츠센터" },
    { id: "wellness",      name: "웰니스 시설" },
  ]},
  { id: "office", name: "업무시설", children: [
    { id: "office-general",  name: "오피스" },
    { id: "coworking",       name: "공유오피스" },
    { id: "public-office",   name: "공공업무시설" },
    { id: "public-service",  name: "공공서비스센터" },
    { id: "admin-welfare",   name: "행정복지센터" },
  ]},
  { id: "lodging", name: "숙박시설", children: [
    { id: "hotel",      name: "호텔" },
    { id: "hostel",     name: "호스텔" },
    { id: "guesthouse", name: "게스트하우스" },
    { id: "pension",    name: "펜션" },
    { id: "resort",     name: "리조트" },
  ]},
  { id: "tourism", name: "관광휴게시설", children: [
    { id: "camping",        name: "캠핑장" },
    { id: "visitor-center", name: "방문자센터" },
  ]},
  { id: "auto", name: "자동차관련시설", children: [
    { id: "parking", name: "주차장" },
  ]},
  { id: "transport",   name: "운수시설",         children: [] },
  { id: "warehouse",   name: "창고시설",         children: [] },
  { id: "recycling",   name: "자원순환관련시설", children: [] },
  { id: "agriculture", name: "동식물관련시설",   children: [] },
];

/* 2차 id → 1차 id 역색인 (필터·표시용) */
const USE_TYPE_INDEX = (() => {
  const idx = {};
  USE_TYPES.forEach((cat) => {
    (cat.children || []).forEach((sub) => { idx[sub.id] = cat.id; });
  });
  return idx;
})();

/* ---------- 마실 코스 (큐레이션 워크) ---------- */
const COURSES = [
  {
    id: "bukchon",
    no: "C-01",
    name: "북촌 골목, 모더니즘과 한옥 사이",
    blurb: "김수근의 검은 벽돌부터 종묘의 회랑까지 — 종로 한복판을 천천히 가로지르는 4시간.",
    curator: { name: "현지", initial: "현", role: "동네 8년차 · 종로 거주", color: "#D3AC2B", verified: true },
    rating: 4.8, reviews: 134, visited: 1284, saved: 412,
    distance: "4.2km", duration: "3시간 40분", elevation: "+120m", difficulty: "보통",
    buildings: ["boan", "kongkan", "jongmyo"],
    type: "도슨트", price: 32000, hasDocent: true,
    schedule: ["10:00", "14:00", "16:30"],
    meetingPoint: "지하철 3호선 안국역 1번 출구",
    cover: "#333D51",
  },
  {
    id: "concrete",
    no: "C-02",
    name: "콘크리트와 빛, 미술관 산책",
    blurb: "리움부터 본태박물관까지 — 콘크리트 한 가지 재료로 빛이 매번 다르게 떨어지는 곳들.",
    curator: { name: "은영", initial: "은", role: "큐레이터 · 미술관 12년", color: "#5A6B7A", verified: true },
    rating: 4.9, reviews: 87, visited: 921, saved: 280,
    distance: "1박 2일", duration: "이틀", elevation: "비행기 필요", difficulty: "여행",
    buildings: ["leeum", "bonte", "whanki"],
    type: "도슨트", price: 280000, hasDocent: true,
    schedule: ["주말 1박 2일 · 월 1회"],
    meetingPoint: "서울역 KTX 출구",
    cover: "#6B6B6B",
  },
  {
    id: "buseoksa",
    no: "C-03",
    name: "영주 부석사, 가을 단풍과 배흘림기둥",
    blurb: "천 년 된 목조 건축을 가장 좋은 빛에서 보는 한나절. 단풍 끝물에 맞춰 운영.",
    curator: { name: "도윤", initial: "도", role: "건축사학자", color: "#9C7E1A", verified: true },
    rating: 4.7, reviews: 58, visited: 482, saved: 198,
    distance: "당일 왕복", duration: "8시간", elevation: "+180m", difficulty: "쉬움",
    buildings: ["buseoksa"],
    type: "도슨트", price: 78000, hasDocent: true,
    schedule: ["10/15", "10/22", "10/29 · 한정"],
    meetingPoint: "동서울터미널 09:00",
    cover: "#9C7E1A",
  },
  {
    id: "ddp-night",
    no: "C-04",
    name: "동대문 야간 건축 투어",
    blurb: "해가 진 뒤에야 본래의 얼굴이 드러나는 비정형 건축, 그리고 주변 가로의 변화.",
    curator: { name: "서경", initial: "서", role: "사진가", color: "#1F2738", verified: false },
    rating: 4.6, reviews: 41, visited: 386, saved: 102,
    distance: "1.8km", duration: "2시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["ddp"],
    type: "셀프", price: 0, hasDocent: false,
    schedule: ["언제든 · 19:30 ~"],
    meetingPoint: "동대문디자인플라자 1번 입구",
    cover: "#1F2738",
  },
  {
    id: "jongmyo",
    no: "C-05",
    name: "종묘 회랑, 가장 긴 비례",
    blurb: "109m의 단일 건물이 어떻게 위엄을 만들어내는지 — 회랑을 따라 천천히 걷는 두 시간.",
    curator: { name: "정현", initial: "정", role: "건축사학자", color: "#1F2738", verified: true },
    rating: 4.8, reviews: 64, visited: 612, saved: 184,
    distance: "1.2km", duration: "2시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["jongmyo", "kongkan"],
    type: "도슨트", price: 22000, hasDocent: true,
    schedule: ["수·토 14:00", "일 11:00"],
    meetingPoint: "종묘 정문 매표소",
    cover: "#1F2738",
  },
  {
    id: "hangang-industrial",
    no: "C-06",
    name: "한강 산업유산 재생, 하루 산책",
    blurb: "정수장이 공원이 되고, 화력발전소가 미술관이 되는 한강 변의 두 번째 삶.",
    curator: { name: "주영", initial: "주", role: "건축평론가", color: "#5A6B7A", verified: true },
    rating: 4.5, reviews: 38, visited: 421, saved: 92,
    distance: "8.4km", duration: "5시간", elevation: "+30m", difficulty: "보통",
    buildings: ["seonyudo"],
    type: "셀프", price: 0, hasDocent: false,
    schedule: ["언제든"],
    meetingPoint: "지하철 9호선 선유도역 2번 출구",
    cover: "#4A5570",
  },
  {
    id: "gangnam-modern",
    no: "C-07",
    name: "강남 모더니즘 사옥 산책",
    blurb: "치퍼필드의 정원, 비뇰리의 도넛, 그리고 그 사이의 30년.",
    curator: { name: "은영", initial: "은", role: "큐레이터", color: "#333D51", verified: true },
    rating: 4.7, reviews: 52, visited: 538, saved: 147,
    distance: "3.2km", duration: "3시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["jongrotower", "amorepacific"],
    type: "도슨트", price: 38000, hasDocent: true,
    schedule: ["토 10:00", "일 14:00"],
    meetingPoint: "지하철 1호선 종각역 1번 출구",
    cover: "#333D51",
  },
  {
    id: "andong-hanok",
    no: "C-08",
    name: "안동 한옥, 천 년의 비례",
    blurb: "봉정사 극락전부터 양진당 종갓집까지, 한옥의 두 얼굴을 1박 2일에.",
    curator: { name: "도윤", initial: "도", role: "건축사학자", color: "#333D51", verified: true },
    rating: 4.9, reviews: 76, visited: 482, saved: 246,
    distance: "1박 2일", duration: "이틀", elevation: "+220m", difficulty: "보통",
    buildings: ["bongjeongsa", "yangjindang"],
    type: "도슨트", price: 220000, hasDocent: true,
    schedule: ["월 1회 · 셋째주 주말"],
    meetingPoint: "안동역 KTX 출구",
    cover: "#333D51",
  },
  {
    id: "yongin-media",
    no: "C-09",
    name: "용인 백남준 + 미디어 아트",
    blurb: "작가의 자필 사인이 건축이 된 곳, 그 안에서 미디어 아트가 작동하는 방식.",
    curator: { name: "최은영", initial: "최", role: "큐레이터", color: "#4A5570", verified: true },
    rating: 4.6, reviews: 29, visited: 268, saved: 71,
    distance: "당일 왕복", duration: "6시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["njpcenter"],
    type: "도슨트", price: 58000, hasDocent: true,
    schedule: ["토 10:00"],
    meetingPoint: "강남역 4번 출구 (셔틀버스)",
    cover: "#4A5570",
  },
  {
    id: "hangeul-family",
    no: "C-10",
    name: "한글박물관, 글자와 건축 사이",
    blurb: "한글 모음의 곡선이 어떻게 외피가 되었는지 — 아이와 함께 걷는 한나절.",
    curator: { name: "민서", initial: "민", role: "에듀케이터", color: "#7A8497", verified: false },
    rating: 4.4, reviews: 23, visited: 192, saved: 38,
    distance: "1.5km", duration: "3시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["hangeulmuseum"],
    type: "셀프", price: 0, hasDocent: false,
    schedule: ["언제든 · 화-일"],
    meetingPoint: "이촌역 2번 출구",
    cover: "#7A8497",
  },
  {
    id: "gwangju-acc",
    no: "C-11",
    name: "광주 ACC, 비어 있는 광장",
    blurb: "옛 전남도청 위에 빛의 숲이 떨어지는 1박 2일. 5·18의 기억과 함께.",
    curator: { name: "한지수", initial: "지", role: "도시연구자", color: "#5A6B7A", verified: true },
    rating: 4.8, reviews: 47, visited: 312, saved: 128,
    distance: "1박 2일", duration: "이틀", elevation: "평지", difficulty: "보통",
    buildings: ["acc"],
    type: "도슨트", price: 198000, hasDocent: true,
    schedule: ["월 1회 · 다섯째주 주말"],
    meetingPoint: "광주송정역 KTX 출구",
    cover: "#5A6B7A",
  },
  {
    id: "gangneung-sea",
    no: "C-12",
    name: "강릉 솔숲, 백색 미술관",
    blurb: "동해를 마주 본 리처드 마이어의 흰 입방체와 솔숲의 빛.",
    curator: { name: "도윤", initial: "도", role: "여행 작가", color: "#CBD0D8", verified: true },
    rating: 4.7, reviews: 89, visited: 724, saved: 312,
    distance: "당일 왕복", duration: "8시간", elevation: "평지", difficulty: "쉬움",
    buildings: ["soeul"],
    type: "도슨트", price: 84000, hasDocent: true,
    schedule: ["토 09:00", "일 09:00"],
    meetingPoint: "서울역 KTX 강릉선",
    cover: "#B6C9D8",
  },
  {
    id: "wonju-museum",
    no: "C-13",
    name: "원주 뮤지엄 산, 콘크리트와 빛",
    blurb: "안도 다다오의 200m 회랑. 산을 따라 천천히 흐르는 1박 2일.",
    curator: { name: "은영", initial: "은", role: "큐레이터", color: "#6F6F6F", verified: true },
    rating: 4.9, reviews: 124, visited: 1284, saved: 482,
    distance: "1박 2일", duration: "이틀", elevation: "+180m", difficulty: "보통",
    buildings: ["museumsan"],
    type: "도슨트", price: 240000, hasDocent: true,
    schedule: ["월 2회 · 첫째·셋째주 주말"],
    meetingPoint: "서울역 KTX 출구",
    cover: "#6F6F6F",
  },
  {
    id: "jeju-bonte",
    no: "C-14",
    name: "제주 본태박물관, 보자기와 콘크리트",
    blurb: "한라산 자락의 회색 상자 다섯 채. 한국 전통 공예와 안도의 콘크리트가 마주 보는 2박 3일.",
    curator: { name: "지은", initial: "지", role: "큐레이터", color: "#6B6B6B", verified: true },
    rating: 4.8, reviews: 86, visited: 638, saved: 204,
    distance: "2박 3일", duration: "사흘", elevation: "+250m", difficulty: "여행",
    buildings: ["bonte"],
    type: "도슨트", price: 480000, hasDocent: true,
    schedule: ["계절 한정 · 가을·봄"],
    meetingPoint: "제주공항 도착장",
    cover: "#6B6B6B",
  },
  {
    id: "yanggu-park",
    no: "C-15",
    name: "양구 박수근, 마을 한복판의 미술관",
    blurb: "작가의 회벽 같은 질감이 그대로 건축이 된 작은 미술관. 마을과 함께 천천히.",
    curator: { name: "주영", initial: "주", role: "건축평론가", color: "#6B7484", verified: true },
    rating: 4.5, reviews: 18, visited: 142, saved: 28,
    distance: "당일 왕복", duration: "10시간", elevation: "평지", difficulty: "여유",
    buildings: ["parkmuseum"],
    type: "셀프", price: 0, hasDocent: false,
    schedule: ["언제든 · 토·일"],
    meetingPoint: "동서울터미널 양구행",
    cover: "#6B7484",
  },
  {
    id: "seoul-mmcas",
    no: "C-16",
    name: "삼청동 현대미술관, 마당의 미술관",
    blurb: "옛 기무사 터에 흩어진 8개의 작은 매스. 종친부 한옥과 함께 걷는 오후.",
    curator: { name: "최은영", initial: "최", role: "큐레이터", color: "#B0A99C", verified: true },
    rating: 4.7, reviews: 96, visited: 1840, saved: 412,
    distance: "2.4km", duration: "3시간", elevation: "+45m", difficulty: "쉬움",
    buildings: ["mmcas", "geunjeongjeon"],
    type: "도슨트", price: 32000, hasDocent: true,
    schedule: ["수·토 14:00"],
    meetingPoint: "안국역 1번 출구",
    cover: "#B0A99C",
  },
];

/* ---------- 외부 공간 (숙박/식음/체험) ---------- */
const EXTERNAL_SPACES = [
  {
    id: "boanstay",
    name: "보안스테이 1942",
    building: "boan",
    type: "숙박", typeIcon: "🛏",
    summary: "통의동 보안여관의 신관. 옛 여관의 비례를 살린 5개 객실.",
    partner: "마이리얼트립", partnerLogo: "MRT",
    minPrice: 220000,
    href: "#",
  },
  {
    id: "sansacafe",
    name: "산사 다실",
    building: "buseoksa",
    type: "식음", typeIcon: "🍵",
    summary: "부석사 진입로 옆 작은 다실. 산에서 길어 올린 물로 차를 낸다.",
    partner: "캐치테이블", partnerLogo: "CT",
    minPrice: 18000,
    href: "#",
  },
  {
    id: "jejuworkshop",
    name: "콘크리트 워크숍",
    building: "bonte",
    type: "체험", typeIcon: "🧱",
    summary: "안도 다다오 건축을 모티프로 한 콘크리트 소품 만들기 (2시간).",
    partner: "프립", partnerLogo: "FR",
    minPrice: 65000,
    href: "#",
  },
];

/* ---------- 유저 ---------- */
const USER = {
  name: "민서",
  handle: "@minseo",
  initial: "민",
  color: "#D3AC2B",
  joined: "2024년 3월",
  bio: "걷는 속도로 도시를 보는 사람. 한옥과 콘크리트를 똑같이 좋아함.",
  visitedCount: 23,
  savedBuildings: 47,
  savedCourses: 8,
  following: 12,
  followers: 38,
};

/* ---------- 예약 내역 ---------- */
const BOOKINGS = [
  {
    id: "B2026-0418",
    courseId: "bukchon",
    date: "2026.06.15 (토)",
    time: "10:00",
    people: 2,
    price: 64000,
    status: "예정",
  },
  {
    id: "B2026-0301",
    courseId: "concrete",
    date: "2026.07.20 (토) ~ 21",
    time: "1박 2일",
    people: 1,
    price: 280000,
    status: "예정",
  },
  {
    id: "B2025-1124",
    courseId: "ddp-night",
    date: "2025.11.18 (화)",
    time: "19:30",
    people: 3,
    price: 0,
    status: "완료",
  },
];

/* ---------- 권리 관리용 자료 (관리자 화면) ---------- */
const ASSETS = [
  { id: "A-3201", building: "kongkan", name: "공간사옥_외관_가을_001.jpg",  type: "사진",      uploader: "한지수", owner: "한지수",          consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3202", building: "kongkan", name: "공간사옥_평면도_원본.pdf",     type: "도면",      uploader: "마실맵", owner: "건축가 유족",      consent: "대기", split: "유족 60% · 마실맵 40%",        status: "대기" },
  { id: "A-3203", building: "whanki",  name: "환기미술관_3D모델_v2.glb",    type: "3D",        uploader: "우규승", owner: "우규승 외 2명",    consent: "보류", split: "설계자 50% · 협력 30% · 마실맵 20%", status: "보류" },
  { id: "A-3204", building: "buseoksa",name: "부석사_무량수전_드론_004.jpg", type: "사진",      uploader: "도윤",   owner: "도윤",            consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3205", building: "leeum",   name: "리움_진입홀_다이어그램.svg",   type: "다이어그램", uploader: "은영",   owner: "은영",            consent: "완료", split: "100%",                       status: "공개" },
  { id: "A-3206", building: "ddp",     name: "DDP_야간_시퀀스_012.jpg",     type: "사진",      uploader: "서경",   owner: "서경 외 1명",      consent: "대기", split: "촬영 70% · 스타일링 30%",     status: "대기" },
  { id: "A-3207", building: "bonte",   name: "본태_평면배치.pdf",           type: "도면",      uploader: "마실맵", owner: "안도다다오 사무소", consent: "보류", split: "원저작자 80% · 마실맵 20%",    status: "보류" },
  { id: "A-3208", building: "boan",    name: "보안여관_재현_도면.dwg",       type: "도면",      uploader: "마실맵", owner: "마실맵",          consent: "완료", split: "100%",                       status: "공개" },
];

Object.assign(window, { BUILDINGS, COLLECTIONS, REGIONS, TYPES, USE_TYPES, USE_TYPE_INDEX, COURSES, EXTERNAL_SPACES, USER, BOOKINGS, ASSETS });
